apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: autoscale
spec:
  containers:
    - name: load-generator
      image: busybox
      command: ["sh", "-c", "while sleep 0.01; do wget -q -O- http://php-apache; done"]

  imagePullSecrets:
    - name: docker-cred
